def startscreen():
    print("+--------------------------------------------------------------+")
    print("|        WELCOME TO HYPERMARKET MAX (employee edition)         |")
    print("+--------------------------------------------------------------+")
    print("                                                                ")
    print("+--------------------------------------------------------------+")
    print("| WHAT DO YOU NEED HELP WITH ?                                 |")
    print("+--------------------------------------------------------------+")
    print("|                                                              |")
    print("| Add employees                       TYPE 1                   |")
    print("| View employee list                  TYPE 2                   |")
    print("| End this endless loop               TYPE 3                   |")
    print("+--------------------------------------------------------------+")
startscreen()
